version = "3.8.1"
runner.dialect = scala212

maxColumn = 100

indent.main = 2
indent.significant = 2

align.preset = more
align.tokens."+" = [
  { code = "->", owner = "Term.ApplyInfix" }
]

newlines.alwaysBeforeElseAfterCurlyIf = false
newlines.beforeCurlyLambdaParams = multilineWithCaseOnly

rewrite.rules = [RedundantBraces, SortImports]
rewrite.redundantBraces.stringInterpolation = true
